name: Mobile tests

on:
  push:
    paths:
      - test/**
      - .github/workflows/workflow_mobile.yml

jobs:
  harmonix-mobile:
    name: Build and test harmonix_mobile
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1.1.0
        with:
          path: .tool-versions
        id: tool_versions
      - name: Install SQLite3
        run: |
          brew install sqlite3
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.tool_versions.outputs.flutter }}
          cache: true
      - run: flutter pub get
      - run: dart ./scripts/init_powersync_core_binary.dart
      - run: flutter test --dart-define SQLITE_BIN=$(which sqlite3)
